### ISSUE TITLE
Change 1-D grid functions to classes

### ISSUE THREAD

**Issue by FarnazH** [theochem/grid#118]
Change functions in `onedgrid` module to be subclasses of the `OneDGrid` grid, so that we can add `pre_defined(atnum, preset)` class method for initializing 1-D grids.

**Comment by tczorro** [comment]
@FarnazH @PaulWAyers 
`OneDGrid` inherit constructor from `Grid(pts, wts)`. If we add each method as a subclass of `OneDGrid` as well as keeping the constructor API style as `onedgrid_method(num_pts)`.  Then we need to reconstruct the `__init__` in `OneDGrid`, which I am not very keen on.
`Solution 1`: We can just group all the `onedgrid_methods` into a New class `OneDGridMethod` that return a `OneDgrid` instance, in this case we can retain the uniformity  of `grid` constructor and style and keep all the old `onedgrid_methods` API.
`Solution 2`: We just change the initializer in `OneDGrid(pts, wts)` to `OneDGrid(num_pts)`.
`Solution 3`: Retain the `OneDGrid(pts, wts)` initializer method,  but also add another constructor such as `OneDGrid.from_npoints(num_pts)`

I am personally in favour of `S1` since it requires the minimal changes, while still keep the uniformity of `Grid` classes

**Comment by FarnazH** [comment]
@tczorro, can you please elaborate on `Solution 1`? Are you thinking about a class factory?

I like to keep the current constructor of `OneDGrid`, which is `__init__(self, points, weights, domain=None)`, so I like `Solution 3` better (as compared to `Solution 2`).

What do you think @tovrstra?

**Comment by tczorro** [comment]
@FarnazH So the solution 1 is a little bit tricky when implement. So the idea is rather to make all the functions into a `OneDGrid` subclass. We just create a new `ABC` like `OneDGenerator`, all the subclass of `OneDGenerator` returns `OneDGrid` instance.

To do so, in the
```python
class A:
   def __new__(cls, val):
          return B(val)
   def __init__(self, val):
          self.val = val
```
In this case, the class A will return a instance of class B when call the initializing function.

**Comment by tovrstra** [comment]
The current API may still be good when it is made PEP-8 compliant. Having functions with CamelCase is confusing, without much added value. Subclassing would only be strictly needed when you rely on polymorphism, i.e. when the subclasses modify the behavior of the base class. I don't believe that is that case, the behavior is the same, just with different data.

**Comment by tczorro** [comment]
Let's try `**solution2**` for now
