### ISSUE TITLE
Porcelain

### ISSUE THREAD

**Issue by FarnazH** [theochem/grid#13]
- A function which takes atomic numbers, atomic coordinates, and some description of grid and returns an instance of `MolecularGrid` class. (Note: here is where `tv-*.txt` points stored in needed; check #11)

**Comment by PaulWAyers** [comment]
Also:
* A function that converts a function on a grid to its potential (Poisson solve) or converts a potential on a grid to a function (differentiation).

**Comment by tovrstra** [comment]
Regarding order of implementation: the poisson solver also needs the ODE solver, so it needs to be implemented first. I would suggest to split the ODE, Poisson solver, multipole decomposition and evaluation into separate issues or pull requests. Doing it all together is far too much for one PR.

**Comment by FarnazH** [comment]
> Regarding order of implementation: the poisson solver also needs the ODE solver, so it needs to be implemented first. I would suggest to split the ODE, Poisson solver, multipole decomposition and evaluation into separate issues or pull requests. Doing it all together is far too much for one PR.

@tczorro looking at this closed issue again, I was wondering whether multipole decomposition and evaluation is implemented?

**Comment by PaulWAyers** [comment]
- I don't see evaluating the Laplacian here. That's important as the "inverse" of the Poisson solver.
- Spherical average. *Must* be around an atomic center. 
- Multipole moments (for an arbitrary center)

1. The Laplacian evaluation is relatively straightforward and may be implemented, but I couldn't find it.
2. Spherical Average notes 
3. Moments notes

**Comment by PaulWAyers** [comment]
Spherical Average Notes
[Sphericalaverage.md](https://github.com/theochem/grid/files/8712404/Sphericalaverage.md)
[Sphericalaverage.pdf](https://github.com/theochem/grid/files/8712405/Sphericalaverage.pdf)

**Comment by PaulWAyers** [comment]
Spherical average notes updated, hat tip especially @Ali-Tehrani  and @FarnazH for clarifications.
[Sphericalaverage.md](https://github.com/theochem/grid/files/8720551/Sphericalaverage.md)
[Sphericalaverage.pdf](https://github.com/theochem/grid/files/8720552/Sphericalaverage.pdf)

**Comment by PaulWAyers** [comment]
To generate spherical moments, we can use the code in `denspart` (which generates spherical harmonics). 
https://github.com/theochem/denspart/blob/082cf5df6e0438cef06589cb9d371ca34dbee621/denspart/properties.py#L129

**Comment by PaulWAyers** [comment]
Note on multipole moments are attached here.
[MomentsGrid.md](https://github.com/theochem/grid/files/8879580/MomentsGrid.md)
[MomentsGrid.pdf](https://github.com/theochem/grid/files/8879581/MomentsGrid.pdf)

**Comment by tczorro** [comment]
@PaulWAyers I think most those changes are done by Toon. So I am very aware of those.

**Comment by PaulWAyers** [comment]
Talking with @tovrstra @evohringer and @FarnazH yesterday, it seems best to add moments as an integration option, in the base class. The only caveat is that we would need to be very careful with periodic boundary conditions. That's something that can be, I think, handled in some elegant way (that I haven't figured out or even really thought about yet). (It's a standard problem scientifically, but code-wise it is trickier.)

Also, we should perhaps take spherical harmonics (by duplication) from the new `denspart`. The reason is that `scipy` spherical harmonics seem to not use a recursion. That is not a huge deal for the moments (where you do not compute to very high order) but when we are doing interpolation/differential-eq-solving, we compute spherical harmonics up to very high order (degree of the angular grid // 2).  Note that the normalization used there is appropriate for moments (good for that) but not great for other bits of the code.
https://github.com/theochem/denspart/blob/082cf5df6e0438cef06589cb9d371ca34dbee621/denspart/properties.py#L129

Another alternative is to use `shtools`, which may be faster (Fortran code with Python wrapper). They will compute all the spherical harmonics up to an order, but don't seem to be vectorized (you can only compute one point at a time). They support real or complex spherical harmonics with a wide variety of normalizations.
    https://shtools.github.io/SHTOOLS/pyspharm.html

A final alternative would to be to code the recursion and use some sort of dynamic programming, but I think the memory obligations from the caching would be crazy.

**Comment by PaulWAyers** [comment]
Reminder to self @PaulWAyers to figure out the algorithm in `denspart` for solid harmonics so we can document it.

**Comment by PaulWAyers** [comment]
For moments, we can use as tests a function (e.g. a Gaussian) that is centered at the origin and also one centered off the origin. The change in solid-harmonic coefficients when you shift the origin of a moment expansion is analytically computable. 
- There is code in Julia that [shifts the origin of a solid harmonic expansion](https://juliapackages.com/p/sphericalharmonicexpansions)

There are also some analytic formulas available.
- [see page 66](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.56.5257&rep=rep1&type=pdf) 
- Ruedenberg found a classical result, which is simplified in Eq. (8) of [this reference](https://onlinelibrary.wiley.com/doi/10.1002/qua.24356)
- There is also a result in [this reference](https://asa.scitation.org/doi/10.1121/1.5041742)
- A tabulation of the coefficients for translation/rotation is available [in the supplementary material of this reference](https://pubs.acs.org/doi/full/10.1021/ci0256539)

**Comment by PaulWAyers** [comment]
> Talking with @tovrstra @evohringer and @FarnazH yesterday, it seems best to add moments as an integration option, in the base class. The only caveat is that we would need to be very careful with periodic boundary conditions. That's something that can be, I think, handled in some elegant way (that I haven't figured out or even really thought about yet). (It's a standard problem scientifically, but code-wise it is trickier.)
> 
> Also, we should perhaps take spherical harmonics (by duplication) from the new `denspart`. The reason is that `scipy` spherical harmonics seem to not use a recursion. That is not a huge deal for the moments (where you do not compute to very high order) but when we are doing interpolation/differential-eq-solving, we compute spherical harmonics up to very high order (degree of the angular grid // 2). Note that the normalization used there is appropriate for moments (good for that) but not great for other bits of the code. https://github.com/theochem/denspart/blob/082cf5df6e0438cef06589cb9d371ca34dbee621/denspart/properties.py#L129
> 
> Another alternative is to use `shtools`, which may be faster (Fortran code with Python wrapper). They will compute all the spherical harmonics up to an order, but don't seem to be vectorized (you can only compute one point at a time). They support real or complex spherical harmonics with a wide variety of normalizations. https://shtools.github.io/SHTOOLS/pyspharm.html
> 
> A final alternative would to be to code the recursion and use some sort of dynamic programming, but I think the memory obligations from the caching would be crazy.

We implemented a recursion for spherical harmonics from the literature. 
Journal of Geodesy 76.5 (2002): 279-299.
