### ISSUE TITLE
LinearInfiniteRTransform behaviour has memory

### ISSUE THREAD

**Issue by marco-2023** [theochem/grid#185]
The `LinearInfiniteRTransform` class retains memory about the first grid in which is used. This affects the behaviour of its `transform_1d_grid` method.  When the same instance of the class is used to transform the points of two linear uniform grids with the same number of points but different ranges, the algorithm behaviour depends on the first grid in which is used.

**Example:** 
```python
from grid.onedgrid import UniformInteger    
from grid.rtransform import LinearInfiniteRTransform
import numpy as np

npoints=5
onedgrid_1=UniformInteger(npoints)
onedgrid_2=UniformInteger(npoints)

# create linear infinite R transforms (intemediate)
rtransform_1=LinearInfiniteRTransform(0., 3.)
# change the interval of the second grid to [0, 3]
onedgrid_2=rtransform_1.transform_1d_grid(onedgrid_2)

# create final linear infinite R trasform
rtransform_f=LinearInfiniteRTransform(0., 1.)
rtransform_f_virgin=LinearInfiniteRTransform(0., 1.)

# transform the two grids with the same R transform
rgrid_1=rtransform_f.transform_1d_grid(onedgrid_1)
rgrid_2=rtransform_f.transform_1d_grid(onedgrid_2)
rgrid_2_virgin=rtransform_f_virgin.transform_1d_grid(onedgrid_2)

# print the R transformed grids
print("Printing one-step R transformed grid points:")
print(rgrid_1.points)
print("Printing two-step R transformed grid points:")
print(rgrid_2.points)
print("Printing two-step R transformed grid points (virgin):")
print(rgrid_2_virgin.points)
```

The output is:
```{verbatim}
Printing one-step R transformed grid points:
[0.   0.25 0.5  0.75 1.  ]
Printing two-step R transformed grid points:
[0.     0.1875 0.375  0.5625 0.75  ]
Printing two-step R transformed grid points (virgin):
[0.   0.25 0.5  0.75 1.  ]
```
It can be seen how when the `rtransform_f` instance is used the second time, the scaling is not properly done.  This is due to the method `set_maximum_parameter_b` of `LinearInfiniteRTransform` (line 761 of transform module). If a new instance (virgin) of the class is used, the method works.

Is this a feature of a bug?

**Comment by Ali-Tehrani** [comment]
Thank you @marco-2023. This also affects `ExpRTransform`, and `PowerRtransform` and is related to the fix in issue #143.  This is a feature rather than a bug. 

The dilemma of setting the b-parameter in the way that fixes your problem is if the user wants to use the functions `inverse`, `deriv` or `transform` again with the same parameters.  It is written in the code document [here](https://github.com/theochem/grid/blob/71876b912b50c1ab7343e74f86754255bcac93e9/src/grid/rtransform.py#L709-L710) and [here](https://github.com/theochem/grid/blob/71876b912b50c1ab7343e74f86754255bcac93e9/src/grid/rtransform.py#L732-L735) that the b parameter is set from the first grid that it is used.  

The solutions to make it more clear for the users is to either:

1. Require the user to define the `b` parameter in the initializer `__init__` so that it is apparent.  Currently, it is automatic.
2. Write out a warning if the maximum of the grid being used is different from the `b` parameter.  This adds an additional O(N) cost, but for radial grids N is small, so it's fine.

**Comment by marco-2023** [comment]
Thank you very much @Ali-Tehrani for clearing my doubts. I will close this issue then (as it is not an issue at all).

**Comment by PaulWAyers** [comment]
@marco-2023 and @Ali-Tehrani the main solution to this issue is, as Ali notes, just documentation/examples. I think option #2 is probably the way to go, and then clearify the documentation that the `b` parameter is permanent.
